server:
  host: "0.0.0.0"
  port: "8080"
db:
  migrate_dir: "migrate"
  driver: "postgres"
  postgres:
    connection_dsn: "postgres://user123:pass123@postgres:5432/postgres?sslmode=disable"
keys:
  access_key: "super_secret_access_key_1q2w3e4r5"